version: "3.5"

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    image: nginx
    ports:
      - "8090:80"
    working_dir: /var/www
    volumes:
      - ./:/var/www
  fpm:
    container_name: fpm
    build:
      dockerfile: docker/fpm.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
  pgsql:
    container_name: pgsql
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5434:5432"
    volumes:
      - ./docker_var/pgdata:/var/lib/postgresql/data:rw
